### ISSUE TITLE
Version 5.2.2 - Microsoft.Identity.Client 4.56.0 Vulnerability

### ISSUE THREAD

**Issue by timjen3** [linq2db/linq2db.LINQPad#114]
Linqpad emits the following warning when using version 5.2.2 of linq2db.LINQPad:
```
Warning for dependency Microsoft.Identity.Client 4.56.0:
Level 1 vulnerability (Moderate)
https://github.com/advisories/GHSA-m5vv-6r4h-3vj9
```

**Comment by sjrulandch** [comment]
Not a good sign if a security issue has been open for over a month...

Fix should be as easy as rebuilding with the latest dependencies.

**Comment by sdanyliv** [comment]
We will prepare build soon. As it is not critical we plan to relase It after releasing `linq2db` 6.preview-2.

**Comment by MaceWindu** [comment]
Looks like preview.2 release will take more time than we expected, so I will release linqpad update today
