### ISSUE TITLE
DB2 for iSeries support removed?

### ISSUE THREAD

**Issue by mhellsten** [linq2db/linq2db.LINQPad#118]
The DB2 iSeries provider seems to have been removed in https://github.com/linq2db/linq2db.LINQPad/pull/82. Is it still possible to use iSeries with linq2db.LINQPad via Linq2DB4iSeries somehow? If so, can somebody help me with some hints as to how? Thanks!

**Comment by MaceWindu** [comment]
Only by using custom build.

I will try to enable it in next release, but no guaranties as same issues still persist:
- we have no way to test wether it works at all as we don't have access to iSeries database
- for major releases we usually dont have provider released yet with compatibility with current linq2db version so we have nothing to enable

**Comment by mhellsten** [comment]
Thanks, @MaceWindu! I'm not familiar enough with these libraries (yet) to have a good idea of the level of complexity involved, but if you think it should be fairly easy, and are able to outline what needs to happen, I may be interested in giving it a try myself. I have access to iSeries with Db2 Connect licensing for testing.

**Comment by mhellsten** [comment]
Thanks, @MaceWindu! 

I made those changes, but it throws here:
```
	public virtual IDataProvider GetDataProvider(string providerName, string connectionString)
	{
		return DataConnection.GetDataProvider(providerName, connectionString)
			?? throw new LinqToDBLinqPadException($"Can not activate provider '{providerName}'");
	}
```

```
Can not activate provider 'DB2.iSeries'
```

But, actually, just doing this with Linq2DB4iSeries by itself in LINQPad...

```
var options = new DataOptions().UseDB2iSeries(connectionString);
var db = new DataConnection(options);
```
... results in this:
```
DataProvider 'DB2.iSeries' not found.
```
...so I'm a bit confused. Any ideas? 🙂

**Comment by MaceWindu** [comment]
That actually expected. External provider need to be not registered in `LinqToDB` or instance of provider provided explicitly.

With `UseDBiSeries` call you need to use one of those two overloads which create provider isntance: https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/blob/master/Source/ISeriesProvider/DB2iSeriesDataOptionsExtensions.cs#L43-L73

And to register provider in `LinqToDB` following code could be used:
```cs
DataConnection.AddProviderDetector(DB2iSeriesTools.ProviderDetector)
```

**Comment by mhellsten** [comment]
@MaceWindu, this is working now, thanks! Anything in particular you want me to do for the testing? I'm not sure how `TypeRenderingTests.txt` is supposed to be used.

Do you want me to open a PR?

https://github.com/linq2db/linq2db.LINQPad/compare/master...mhellsten:linq2db.LINQPad:master

(BTW/FWIW, just the AddProviderDetector call was sufficient to get both working.)

**Comment by MaceWindu** [comment]
> Do you want me to open a PR?

Yes, please send a PR. I will review it and release new version

**Comment by mhellsten** [comment]
Please see https://github.com/linq2db/linq2db.LINQPad/pull/120
Thanks!
