### ISSUE TITLE
Feat. Request: Add Support For Intersystems Caché/IRIS

### ISSUE THREAD

**Issue by FreeYourMinds** [linq2db/linq2db.LINQPad#123]
# Feature Request

Could you please consider adding support for `Caché` or now `IRIS` from Intersystems?

For further details refer to [Using .NET and the ADO.NET Managed Provider with Caché](https://docs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=GBMP)

**Comment by MaceWindu** [comment]
New database requests should go there https://github.com/linq2db/linq2db/issues/1014

**Comment by FreeYourMinds** [comment]
Understood, placed the request at the proper issue
