### ISSUE TITLE
IBM.Data.DB2.iSeries DLL

### ISSUE THREAD

**Issue by maxcoats** [linq2db/linq2db.LINQPad#15]
![image](https://user-images.githubusercontent.com/14117946/48272584-878d8100-e404-11e8-8deb-2c63e34b9c6e.png)

Any thoughts on this?

**Comment by sdanyliv** [comment]
@RoyC-Retail-Assist, can you help in this? Main problem that we have no testing environment for iSeries.

**Comment by RoyC-Retail-Assist** [comment]
@maxcoats - can you give me some details of what you are doing when you get the issue?  what is the structure of the table you are trying to access etc.

**Comment by MaceWindu** [comment]
I think I know the reason. For some reason we ship iseries v13 assembly with linqpad integration, but it expects v12. As quickfix try to remove or replace it with v12 assembly under c:\ProgramData\LINQPad\Drivers\DataContext\  root

**Comment by maxcoats** [comment]
![image](https://user-images.githubusercontent.com/14117946/48275093-5617b400-e40a-11e8-825c-71935d1c257d.png)

**Comment by MaceWindu** [comment]
Even if it is not the reason - we should remove IBM.Data.DB2.iSeries.dll from linqpad integration and use version from GAC

**Comment by RoyC-Retail-Assist** [comment]
I'm getting a different problem when it is populating the tables.

![image](https://user-images.githubusercontent.com/16333438/48275309-174f2180-e43d-11e8-8e6c-de1e22ee8a28.png)

I'll get the source and try to triage what is going on but it won't be until Monday.

**Comment by MaceWindu** [comment]
That's strange. It's one of fixes in 2.5.1 integration. Maybe you use previous version? If it is recent version - fill issue here with bad generated code sample

**Comment by maxcoats** [comment]
c:\ProgramData\LINQPad path does not contain a drivers directory for me.

**Comment by MaceWindu** [comment]
Well, maybe linqpad stores them somewhere else on your machine

**Comment by maxcoats** [comment]
After driver change to v12 same error :(

**Comment by MaceWindu** [comment]
I will install iseries provider tomorrow and try to debug it tomorrow without database.
Could you provide some details on versions you use to confirm that we all work with same versions:
- linqpad
- linq2db.linqpad
- iSeries Access for Windows driver

**Comment by maxcoats** [comment]
linqpad v5.31.00
linq2db.linqpad v2.5.1

![image](https://user-images.githubusercontent.com/14117946/48277650-e6f18e00-e410-11e8-88c5-64eb95c6a8eb.png)

**Comment by RoyC-Retail-Assist** [comment]
@maxcoats  The iSeries provider has been tested against iAccess V 7 Release 0 SI55797.  I'm guessing that XML column type was introduced after V6.

@MaceWindu I'll do some debugging later this evening on the LinqPad stuff as I would expect it to work ok on my machine.

**Comment by maxcoats** [comment]
Ahh, sorry I missed that. Will have to try and build with my patched version of linqtodb4iseries.

Thanks everyone!

**Comment by maxcoats** [comment]
Confirmed this is straight from IBM's website
https://www-01.ibm.com/support/docview.wss?uid=isg3T1027163

The 7.1 .NET Provider includes these enhancements:

**Support for the IBM i XML data type**
Support for longer SQL schema names
New property to configure the ConcurrentAccessResolution
Support for multi-row UPDATE, DELETE, and MERGE using the iDB2Command.AddBatch method
Class interfaces and technical information is now integrated with Visual Studio

**Comment by MaceWindu** [comment]
Glad to hear that it is solved. 
@RoyC-Retail-Assist It would be great if you could you update your provider readme to mark v7.1 as min version requirement, or even do it in code to throw exception with explanatory text.
