### ISSUE TITLE
Sql.Expression attribute not working from MyExtensions in LINQPad

### ISSUE THREAD

**Issue by Falthazar** [linq2db/linq2db.LINQPad#26]
I have this extension method defined in the MyExtensions file in LINQPad:
```C#
[LinqToDB.Sql.Expression("({0} IS NULL OR Len({0}) IS NOT NULL AND Len({0}) = 0)", IsPredicate = true)]
public static bool IsNullOrEmpty(this string str) => string.IsNullOrEmpty(str);
```

However, when I try and use it in another query it doesn't work and I get:
`LinqException: 'i.TableProperty.IsNullOrEmpty()' cannot be converted to SQL.`

If I move the extension method to the actual query file it works just fine, however. 
I do apologize if this isn't the right place for this. I'm not too familiar with attributes, so not sure if this is me misunderstanding something (probably) or something with LINQPad.

**Comment by MaceWindu** [comment]
Not sure what's going on, but it sounds strange - this error means that your query compiled successfully (found extension properly) and then linq2db wasn't able to handle it.

I've tried your extension with `My Extensions` file and it worked fine for me.

**Comment by MaceWindu** [comment]
Could you post your query code?

**Comment by MaceWindu** [comment]
Also linqpad version. I use `v4.59.0 free` for testing.

**Comment by sdanyliv** [comment]
I think here is collision with linq2db's `IsNullOrEmpty` function. We already have this extension function but not mapped to SQL https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Common/Tools.cs#L42

**Comment by Falthazar** [comment]
LinqPad version 5.4
Here is the query:
```C#
Projects.Select(p => new { p.ProjectID, p.ProjectManager })
    .Where(p => !p.ProjectManager.IsNullOrEmpty())
```
I don't have a `using` for LinqToDb nor LinqToDb.Tools in either the query or the extension, so it wouldn't be a collision right?

For reference, this works of course:
```C#
Projects.Select(p => new { p.ProjectID, p.ProjectManager })
    .Where(p => !string.IsNullOrEmpty(p.ProjectManager))
```

**Comment by sdanyliv** [comment]
Just for clarifying. Could you please rename method to `IsNullOrEmptySql`? If problem still exists we will dig here more deeply.

**Comment by Falthazar** [comment]
Renamed it, but still getting the same error :(.
Tried both `IsNullOrEmptySql` and `IsNullOrEmptySqlasdfdsfasdfdsfa` juuust in case.

**Comment by sdanyliv** [comment]
I'm not so familiar with LINQPad. 
How do you define extension method in script? Screenshot can be enough.
Also which type of Driver do you use? Dynamic or using existing model?

**Comment by MaceWindu** [comment]
Tried it  with linqpad 5.40.0 - still works for me.
Only possible fail point I can see now - you load diffrerent version of linq2db for `My Extensions` compared to version, used by linqpad provider. Try to reload it using F4 in `My extensions` file (extension use linq2db v2.9.1, if you have latest version).

**Comment by Falthazar** [comment]
Well'p, yep that was it! My Extensions was using 2.9.1, but the connection was using 2.7.0. I updated the connection driver to 2.9.1 and now it works perfectly. Thank you so much! Can't believe I didn't check that before.
