### ISSUE TITLE
LinqPad 6 support?

### ISSUE THREAD

**Issue by VictorioBerra** [linq2db/linq2db.LINQPad#29]
I renamed the lpx file to lpx6 but it failed to load.

```
Error instantiating type LinqToDB.LINQPad.LinqToDBStaticDriver in C:\Users\bea\AppData\Local\LINQPad\Drivers\DataContext\NetCore\linq2db.LINQPad\linq2db.LINQPad.dll
  - Driver assembly targets .NET Framework. Your driver assembly must target .NET Core 3.   at LINQPad.Extensibility.DataContext.DriverProxy.Instantiator.Instantiate(String assemblyPath, String typeName, String internalID)

Error instantiating type LinqToDB.LINQPad.LinqToDBDriver in C:\Users\bea\AppData\Local\LINQPad\Drivers\DataContext\NetCore\linq2db.LINQPad\linq2db.LINQPad.dll
  - Driver assembly targets .NET Framework. Your driver assembly must target .NET Core 3.   at LINQPad.Extensibility.DataContext.DriverProxy.Instantiator.Instantiate(String assemblyPath, String typeName, String internalID)
```

**Comment by MaceWindu** [comment]
Currently we build against linqpad4, looks like we need to multitarget to support v6 too

**Comment by VictorioBerra** [comment]
@MaceWindu Any progress on this?

**Comment by MaceWindu** [comment]
Sorry, didn't looked into it yet. I'm currently working on another feature, which still needs 2-3 weeks to finalize (don't have much time to work on it).
I plan to look at it as next task alongside with T4 support for #develop as both tasks are kinda related - they need to use .net core for schema load.

**Comment by jogibear9988** [comment]
@VictorioBerra I've created a pull req.
Maybe you could test lpx6 from here:
https://ci.appveyor.com/project/igor-tkachev/linq2db-linqpad/builds/32775124/artifacts

**Comment by VictorioBerra** [comment]
@jogibear9988 thanks for this, I will test first thing tomorrow morning when I get to a computer.

**Comment by VictorioBerra** [comment]
![image](https://user-images.githubusercontent.com/2934507/81605911-cacd0500-9397-11ea-94fe-2c553ef1968a.png)

**Comment by jogibear9988** [comment]
Im not sure this would work. Whene I read this: https://medium.com/@daniel.sagita/using-microsoft-access-in-net-core-b419dbeceab1 it looks like oledb is not supported in netcore

**Comment by jogibear9988** [comment]
but I don't know...
maybe @MaceWindu or @sdanyliv could help with this question

**Comment by MaceWindu** [comment]
linq2db supports access oledb in .net core starting from 3.0 preview 2, odbc from 3.0 rc0

**Comment by jogibear9988** [comment]
so, atm. it will not work, cause the dll does uses 2.9.8
when 3.0 is released i will upgrade the pull req.

**Comment by MaceWindu** [comment]
Guys, check this https://github.com/linq2db/linq2db.LINQPad/pull/32#issuecomment-661090541 comment for preview vesion of v6 plugin

**Comment by MaceWindu** [comment]
Released https://github.com/linq2db/linq2db.LINQPad/releases/tag/v3.0.0
