### ISSUE TITLE
Downloading driver from LinqPad links to a parked domain

### ISSUE THREAD

**Issue by Falthazar** [linq2db/linq2db.LINQPad#30]
So, tried downloading an updated Linq2db driver from the LinqPad dialog box, and it wasn't working. Turns out it links to:
http://tkachev.com/linq2db/linq2db.LINQPad.lpx

Which now looks like a parked domain.

**Comment by MaceWindu** [comment]
whoops, thanks for heads ups!

**Comment by MaceWindu** [comment]
While we are looking into it, you can downoad latest version from release page https://github.com/linq2db/linq2db.LINQPad/releases/tag/v2.9.3

**Comment by MaceWindu** [comment]
Download link updated, but now LinqPad 4 is not able to download driver due to redirects (v5 works fine).

**Comment by Falthazar** [comment]
Awesome, thanks! It works.
