### ISSUE TITLE
SAP Sybase ASE broken

### ISSUE THREAD

**Issue by dandaviscpa** [linq2db/linq2db.LINQPad#33]
I am trying to connect to a Sybase database in Linqpad. After downloading the Linq to DB Connection driver, I choose SAP Sybase ASE as the data provider. I put in the connection string items, then try to connect. I am getting an error that says:
"Unable to find the requested .Net Framework Data Provider. It may not be installed"

Is anyone else able to connect to a sybase database using this driver? What can I do?

**Comment by PillowMetal** [comment]
I have the same problem... it used to work fine with my current configuration and just stopped working one day when LINQPad was updated

LINQPad v5.43
Sybase ASE 15 Developer edition installed

**Comment by MaceWindu** [comment]
You should have properly installed SAP ASE DataAccess drivers to connect to ASE database from linqpad.

I think we should switch to managed provider from [DataAction](https://github.com/DataAction/AdoNetCore.AseClient) from next release.

**Comment by MaceWindu** [comment]
Guys, if you can use Linqpad v6, I've posted preview here https://github.com/linq2db/linq2db.LINQPad/pull/32#issuecomment-661090541 with managed sybase provider, so you don't need to install local client

**Comment by MaceWindu** [comment]
New version with managed ASE provider released https://github.com/linq2db/linq2db.LINQPad/releases/tag/v3.0.0

**Comment by dandaviscpa** [comment]
Thank you! This works great!

**Comment by MaceWindu** [comment]
Note that there is one known issue with broken varbinary columns support, will be fixed in next release, as it requires fix in linq2db
