### ISSUE TITLE
Update target framework to 3.1

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db.LINQPad#36]
Latest version of LINQPad dropped today and all of my linq2db connections started blowing up. This might have been related to VS2019 installing .NET Core 3.0 target pack when I opened an older project.

Long story short, since `linq2db.LINQPad` targets .NET Core 3.0 LINQPad runs it under that framework. That works all the way up until the driver tries to load the `linq2db` assembly which requires .NET Core 3.1.

Can you please bump the target framework to `netcoreapp3.1` and push a new version out to nuget? I don't want to have to go through purging .NET Core 3.0 every time I open an old project 😄 

(I mean, I could build a custom version of the driver, but... yeah, nah)

**Comment by MaceWindu** [comment]
Makes sense. There is no good reason to use 3.0 these days

**Comment by MaceWindu** [comment]
#37
