### ISSUE TITLE
Question - Connection settings for context from assembly

### ISSUE THREAD

**Issue by RoyChase** [linq2db/linq2db.LINQPad#38]
I'm trying to load a data context from an assembly using LinqPad6.  In the dialog I am specifying an appsettings.json file but no matter what I enter, when I try to use the context I'm getting an exception that Configuration 'Default' is not defined.

What should the structure of the settings file be to configure this?

LinqPad6
Linq2DB LinqPad driver 3.1.0.0

**Comment by MaceWindu** [comment]
There is no built-in support for json-based configuration, only app.config connectionStrings supported out-of-box. Not sure if it will work with .net core

**Comment by MaceWindu** [comment]
Probably we need to redesign this configuration screen for linqpad6 (or even v5 too)

**Comment by RoyChase** [comment]
app.config doesn't work either.

Is it a big job to add functionality to load connection strings settings?  I'm happy to have a go if it is likely to be possible?

**Comment by MaceWindu** [comment]
Issue is that compared to app.config's [configuration/connectionStrings](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings-and-configuration-files#the-connectionstrings-section) being a standard mechanism for connection configuration, there is no standard declarative replacement for .net core, so it is not clear what should be implemented.

I think as quick fix we should add connection string field to configuration dialog. Should be an easy task:
- add ui field
- Add configuration using field value to DataConnection in code

**Comment by MaceWindu** [comment]
PRobably we should add support for json configuration schema from here https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings#aspnet-core

but this is task for linq2db (still could be done in linqpad as quick fix)

**Comment by RoyChase** [comment]
If we add a connection string to the configuration dialog then we will also need to specify the provider somehow and, in my case, the name.  It might be easier to actually load a config file to do this if there is a suitable hook from LinqPad.

I'll have play over the next few days.

**Comment by MaceWindu** [comment]
@RoyChase , I've added support for json, but as you said - now to detect provider, connection string name should be in form, recognized by `<DB>Tools.ProviderDetector()` method
