### ISSUE TITLE
Cannot load "System.Runtime, Version=4.2.1.0, PublicKeyToken=b03f5f7f11d50a3a"

### ISSUE THREAD

**Issue by shameleo** [linq2db/linq2db.LINQPad#39]
**Version**: 3.1.0.0
**OS**: Win 10 x64
I have .NET Framework 4.8, .NET Core 2.1 (SDK), .NET Core 3.1 (Desktop runtime) installed.

It happens when I try to add "typed data context" connection (dll depends on .NET Core 2.1 and linq2db 3.2.3).
What can go wrong?

![Screenshot](https://user-images.githubusercontent.com/11148445/110628954-b2469a80-81b4-11eb-93d1-58f0a7ad0349.png)

**Comment by MaceWindu** [comment]
Which version of LinqPAD you use?

**Comment by shameleo** [comment]
@MaceWindu  5.43.00

**Comment by MaceWindu** [comment]
linqpad 5 supports only .net framework, for .net core you should use linqpad6

**Comment by shameleo** [comment]
With linqpad 6 I have `RuntimeBinderException`:
[screenshot](https://user-images.githubusercontent.com/11148445/110899253-ceac1980-8311-11eb-8f8c-5ee83d8ac1fa.png)

**Comment by MaceWindu** [comment]
Looks like it is due the fact that current linqpad driver use linq2db 3.1.4 but your library use 3.2.3 version.
We will release updated driver with 3.3.0 release.

You could try to rebuild driver with newer dependecies (build will generate lpx6 file in source folder)

**Comment by MaceWindu** [comment]
Note that issue is not in version change itself but due to changes in public API between those versions

**Comment by MaceWindu** [comment]
Actually.. 3.3.0 release will take some time, so I will release one based on 3.2.3 today

**Comment by shameleo** [comment]
Actually error is the same with linq2db 3.1.4 or 3.1.0

**Comment by MaceWindu** [comment]
could you try attached version (remove .zip from file name)
[linq2db.LINQPad.lpx6.zip](https://github.com/linq2db/linq2db.LINQPad/files/6129972/linq2db.LINQPad.lpx6.zip)

**Comment by shameleo** [comment]
Still the same error (ver `3.2.0.0`)

I created special assembly for testing with minimalistic type:
```cs
    public class Branch
    {
        [PrimaryKey]
        public int Id;
        public string Region;
    }

    public class Db : DataConnection
    {
        public Db() : base(
            new SqlServerDataProvider(ProviderName.SqlServer2008, SqlServerVersion.v2008), 
            "valid connection string here"
        ) { }

        public ITable<Branch> Branches => GetTable<Branch>();
    }
```
Then published it to make sure all dependencies are near. Full name of custom type is picked correctly. Application config file and connection options are not specified.

**Comment by MaceWindu** [comment]
Thanks! Will release fixed version soon

**Comment by shameleo** [comment]
Finally, it works. Greatly appreciated!
