### ISSUE TITLE
LINQPad 5 AnyCPU error - BadImageFormatException on IBM.Data.DB2.dll

### ISSUE THREAD

**Issue by maximpashuk** [linq2db/linq2db.LINQPad#4]
Windows 10 64-bit.

If using LINQPad 5 - linq2db plugin works fine.
if using LINQPad 5 AnyCPU - linq2db plugin throws exception
![untitled](https://cloud.githubusercontent.com/assets/5028850/19681880/5cdc90f6-9ad5-11e6-9acb-d6cbe102fb2a.png)

I think this happens because IBM.Data.DB2.dll **has platform target x86**
If I open IBM.Data.DB2.dll from Redist folder in this repositiry in JetBrains dotPeek, I can see picture
![untitled2](https://cloud.githubusercontent.com/assets/5028850/19682088/3d80467a-9ad6-11e6-910e-47fb56694673.png)

So I think linq2db plugin should provide two versions on IBM.Data.DB2.dll - x86 and x64 bit editions.
You can do this using [bindingRedirect feature](https://msdn.microsoft.com/en-us/library/b0yt6ck0).

**Comment by ili** [comment]
That would be great if possible. 
Do you know if x64 `IBM.Data.*.dll` and if yes where can we get them?

**Comment by maximpashuk** [comment]
You know, I am not using DB2 at all.
Exception I get thrown when I want to connect to MS SQL Server.

But I googled a link
http://www-01.ibm.com/support/docview.wss?rs=4020&uid=swg27016878

Hope this helps.

I can see that client libraries used in linq2db is outdated (version 9.7 used, but current is 11.1).
I think core lin2db project should be updated to support both x86 and x64 versions.

As for me, I am not sure should linq2db support DB2 at all.

**Comment by ili** [comment]
Thanks a lot!

**Comment by jakesays** [comment]
I just came across this issue. My suggestion is to allow the linqpad driver to function when provider dlls are missing so that the ones we can delete the ones we dont need.

**Comment by NimaAra** [comment]
Any update on this please?

**Comment by ili** [comment]
In next versions we'll switch off loading x86 providers in 64 bit environment.
For now I can only suggest not using Any CPU build :(

**Comment by NimaAra** [comment]
okay, sounds good. Any idea when the next version will be out?

**Comment by halleck1** [comment]
Unfortunately, the fix that you did Igor is not really working (see screenshot below). The problem still exists with the change in the screenshot because the check is done in the runtime, while the BadImageFormatException happens during the assembly loading and binding. Unfortunately, the only real fix for LINQPad AnyCPU on 64 bit OS is to remove all references to the offending assemblies (DB2, Informix and Oracle Native).

I did it and it works after rebuild. Just in case you want to incorporate the changes Igor, I'm also attaching the diff file.

![untitled](https://user-images.githubusercontent.com/3926310/36533593-aad2c0bc-17cc-11e8-8aec-4c9e5552b826.png)
[linq2db.patch.zip](https://github.com/linq2db/linq2db.LINQPad/files/1747521/linq2db.patch.zip)

**Comment by sdanyliv** [comment]
Unfortunately we need more clever solution with dynamic assembly loading.

**Comment by jogibear9988** [comment]
a try catch artound does not help?

**Comment by sdanyliv** [comment]
Project has references, so libraries will be loaded automatically. And proposed solution just removes a lot of providers that do not support x64 mode.

**Comment by jogibear9988** [comment]
Are the Librarys only referenced or are they also used?

**Comment by halleck1** [comment]
The libraries are referenced and hence are automatically loaded by .NET Fusion (assembly loading code). 

There is no clever solution unfortunately unless you want to resort to dynamic assembly loading and wrapping their types. The alternative is rather to produce 2 builds of plugin for x86 and x64 platforms with preprocessor conditions removing the offending pieces of code.

**Comment by sdanyliv** [comment]
It is not too hard to load assemblies dynamically. But i have not time do do that right now.

**Comment by halleck1** [comment]
It's not hard, but you'd need to re-wrap every single class from them in your custom loader. It's just going to be a pain in the neck.

The other alternative could be to hook up to host the main plugin entry point in the new dll which would hook up to the AppDomain.CurrentDomain.AssemblyResolve event and would suppress the exception on 64 bit OS. It would then need to hide those specific providers from the UI as well.

**Comment by halleck1** [comment]
Also, for anyone else looking for the plugin which would work on 64 bit OS - here's the build that works for me.
[linq2db.LINQPad.zip](https://github.com/linq2db/linq2db.LINQPad/files/1748635/linq2db.LINQPad.zip)

**Comment by sdanyliv** [comment]
Working on version that loads data providers dynamically, expect this after 2.0 release.

**Comment by sdanyliv** [comment]
Fixed in #11
