### ISSUE TITLE
not thread safe?

### ISSUE THREAD

**Issue by yuzd** [linq2db/linq2db.LINQPad#45]
```csharp

Parallel.ForEach(rdbList, new ParallelOptions() { MaxDegreeOfParallelism = 4 }, (rdb, loopState) =>
{
	this.Insert(new test
			{
				Guid = guid,
				DataChange_LastTime = DateTime.Now,
			});
});

````

err:

Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.

**Comment by MaceWindu** [comment]
No, database connections are not thread-safe

**Comment by yuzd** [comment]
```
	using DataConnection db = new DataConnection("MySqlConnector","Server=127.0.0.1;Port=3306xxxxxxxxxxxxxxxxxxx");
```

**Comment by MaceWindu** [comment]
To clarify it a bit: database connections in general and in ADO.NET specifically not designed to be thread safe and I actually not aware of any provider to declare being thread-safe in this area. And because DataConnection is an abstraction over database connection, it is also not thread-safe.

**Comment by yuzd** [comment]
ok i got it.. thanks
