### ISSUE TITLE
The type initializer for 'Sap.Data.Hana.Hana.Connector' threw an exception'

### ISSUE THREAD

**Issue by wolfgangschneider** [linq2db/linq2db.LINQPad#5]
Can not use SAP Hana 
Fill in Connection string : Servet=xxxxxx:xxxxx and click test results in : The type initializer for 'Sap.Data.Hana.Hana.Connector' threw an exception'

**Comment by ili** [comment]
Hello, sorry for late response

Are there any more details on exception?

**Comment by wolfgangschneider** [comment]
Hello, sorry for late response too.
In case I cannot copy and past from the error window I used an OCR software. that means it could be that the message is not transformed correct.

System.TypelnitializationException: The type initializer for iSap.Data.Hana.HanaConnection' threw an exception. ---> System.IO.FileLoadException: DLL version mismatch - cannot load libSOLDBCHDB.dll. at Sap.Data.Hana.HanaUnmanagedDII.CheckDIIVersion(Version verAssembly, FileVersionlnfo verDlI, String dllName) at Sap.Data.Hana.HanaUnmanagedDII.CheckDIIVersion() at Sap.Data.Hana.HanaUnmanagedDll..ctor() at Sap.Data.Hana.HanaUnmanagedDll.get_Instance0 at Sap.Data.Hana.HanaConnection..cctor() --- End of inner exception stack trace ---at Sap.Data.Hana.HanaConnection..ctor(String connectionString) at lambda_method(Closure, String ) at LingToDB.DataProvider.DynamicDataProviderBase.CreateConnectionInternal(String connectionString) in iAlinq2dIASource\ DataProvider\ DynamicDataProviderBase.cs:line 69 at LincioDB.DataProvider.DataProviderBase.CreateConnection(String connectionString) in iAlinq2dIASource\ DataProviderWataProviderBase.cs:line 76 at LincioDB.Data.DataConnection.get_Connection() in iAlinq2dIA Source\ DataWataConnection.csdine 493 at LincioDB.Data.DataConnection.CreateCommand() in i: finq2dIASourceWataWataConnection.cs:fine 567 at LincioDB.Data.DataConnection.get_Command() in iAlinq2dIASourceWataWataConnection.cs:line 561 at LincioDB.DataProvider.DataProviderBaseinitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters) in i:\linq2db\Source\ DataProviderWataProviderBase.cs:line 90 at LincioDB.Data.DataConnection.lnitCommand(CommandType commandType, String sql, DataParameter[] parameters, List'1 queryHints) in iNinq2dIASourceWataWataConnection.cs:line 544 at LingToDB.Data.CommandInfo.Execute[T]Q in i:\linq2dIASource\ Data \ CommandInfo.cs:line 339 at LincroDB.DataProvider.SapHana.SapHanaSchemaProvider.GetSchema(DataConnection dataConnection, GetSchemaOptions options) in iAlinq2dIASource‘DataProvider\SapHana \SapHanaSchemaProvider.cs:line 22 at LincioDB.LINQPad.SchemaAndCodeGenerator.<GetItemsAndCode>d_11.MoveNext() in CAprojectAlinq2db-linqpachSource\SchemaAndCodeGenerator.cs:line 60 at System.Collections.Genericlistt.ctor(lEnumerablel collection) at Systemlinq.Enumerable.ToList[TSource](lEnumerablel source) at LincroDB.LINQPadlinciToDBDriver.GetSchemaAndBuildAssembly(lConnectionInfo alnfo, AssemblyName assemblyToBuild, String& nameSpace, String& typeName) in CAprojects\ linq2db-linqpad \Source\ LingToDBDriver.csthne 225 at Sap.Data.Hana.HanaConnection..ctor(String connectionString) at lambda_method(Closure, String ) at LincroDB.DataProvider.DynamicDataProviderBase.CreateConnectionInternal(String connectionString) in i: linq2dRSource\ DataProvider\ DynamicDataProviderBase.cs:line 69 at LincioDB.DataProvider.DataProviderBase.CreateConnection(String connectionString) in i:\linq2dIA Source\ DataProviderWataProviderBase.csline 76 at LincioDB.Data.DataConnection.get_Connection() in i:\linq2dIASource\ DataWataConnection.cs:line 493 at LincioDB.Data.DataConnection.CreateCommand() in iAlinq2dIASourceWataWataConnection.cs:line 567 at LingToDB.Data.DataConnection.get_Command() in i:\linq2dIASource\ DataWataConnection.cs:line 561 at LincioDB.DataProvider.DataProviderBaseinitCommand(DataConnection dataConnection, CommandType commandType, String commandTect, DataParameter[] parameters) in i:\linq2dIA Source\ DataProviderWataProviderBase.cs:line 90 at LincioDB.Data.DataConnectioninitCommand(CommandType commandType, String sql, DataParameter[] parameters, List'1 queryHints) in iAlinq2dIASourceWataWataConnection.cs:line 544 at LincioDB.Data.CommandInfo.Ececute[T]() in i:\linq2dIASource\ Data \CommandInfo.cs:line 339 at LincioDB.DataProvider.SapHana.SapHanaSchemaProvider.GetSchema(DataConnection dataConnection, GetSchemaOptions options) in iAlinq2db\ Source\ DataProvider\SapHana‘SapHanaSchemaProvider.cs:Ime 22 at LingToDB.LINQPad.SchemaAndCodeGenerator.<GetItemsAndCode> d_11.MoveNed() in CAprojects\ linq2db-linqpathSource\SchemaAndCodeGenerator.cs:line 60 at System.Collections.Genericlistt.ctor(lEnumerablel collection) at Systemlinq.Enumerable.ToList[TSource](lEnumerablel source) at LincroDB.LINQPadlinqToDBDriver.GetSchemaAndBuildAssembly(lConnectionInfo alnfo, AssemblyName assemblyToBuild, String& nameSpace, String& typeName) in CAprojects\ linq2db-linqpad \Source\ LincioDBDriver.csiline 225

**Comment by ili** [comment]
I see... it looks like this is the same as for https://github.com/linq2db/linq2db/pull/629 
We do not have a solution yet :(

**Comment by rahuljain257** [comment]
Even I am getting the same error :(

**Comment by sdanyliv** [comment]
Something wrong with your installation. We just cannot load driver. It maybe also problem with 32 or 64 bit versions.

**Comment by MaceWindu** [comment]
I had this issue when used old SAP assembly with recent SAP HANA 2 provider. For linq2db 2.5.0 I've updated assembly to modern version in linq2db repository, so probably it will be fixed in next version.
Will check what version we ship for linqpad. I would suggest to replace `Sap.Data.Hana.v4.5.dll` with one from SAP HANA client installation.
