### ISSUE TITLE
MysqlDriver retrieved the wrong count row 

### ISSUE THREAD

**Issue by HillCat** [linq2db/linq2db.LINQPad#60]
actually, the truth row is 13 but LinqPad always retrieved 10-row data. in the end, I try to delete one row, It is 12 rows, but that retrieved 10 rows again.
![image](https://user-images.githubusercontent.com/41800196/139711326-ca15eaf1-055b-4c5e-8b1b-89d55247139e.png)
[TheTestMysqlDataDemo.zip](https://github.com/linq2db/linq2db.LINQPad/files/7454987/TheTestMysqlDataDemo.zip)

MysqlDataBase info:
Server: MySQL (127.0.0.1 via TCP/IP)
Server type: MySQL
Server version: 5.7.30 - MySQL Community Server (GPL)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

window 10  64bit  Pro 21H1

**Comment by MaceWindu** [comment]
Not sure how to handle it.
It works fine for me in both linqpad 5 and 6, but I don't have mysql 5.7 so used v8 for test

**Comment by MaceWindu** [comment]
If query (on SQL tab) is correct, then I don't think this is our fault - we just display data, received from provider. If you can reproduce issue with raw ADO.NET using `MySqlConnector` - you should report issue there https://github.com/mysql-net/MySqlConnector/issues

**Comment by MaceWindu** [comment]
I will close it. 

Tried provided script with mysql 5.5 and 8.0 without success. Probably there is an issue with user's database or `MySqlConnector` provider. We display all data we received from provider, which means query returned only 10 records for some unknown reason.
