### ISSUE TITLE
Using this driver results in a warning (System.DirectoryServices.Protocols 5.0.0 vulnerability)

### ISSUE THREAD

**Issue by jswolf19** [linq2db/linq2db.LINQPad#63]
When using this driver in LINQPad 7.3.9, a warning is emitted at the beginning of the run:

> **Warning:** LINQPad has identified the following vulnerabilties in NuGet package System.DirectoryServices.Protocols 5.0.0:
> 
> Level 1 (Moderate): https://github.com/advisories/GHSA-9cxh-gqpx-qc5m
> Try updating NuGet packages to latest. You can suppress this warning in Edit | Preferences > Advanced > Execution.

The dependency tree seems to be:
- [linq2db 3.6.0](https://github.com/linq2db/linq2db/blob/d441981e6c1baf40a44c230cd28a08eccf626b6f/Directory.Packages.props#L104)
  - [Oracle.ManagedDataAccess.Core 3.21.4](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/3.21.4#dependencies-tab)
    - System.DirectoryServices.Protocols 5.0.0

This should be resolved by bumping the linq2db version used to either 3.7.0 or 4.0.0.
- [linq2db 3.7.0](https://github.com/linq2db/linq2db/blob/fc4b1f760ce3566f9fa8beeb7995b2a054eb8e99/Directory.Packages.props#L114)
  - [Oracle.ManagedDataAccess.Core 3.21.50](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/3.21.50#dependencies-tab)
    - System.DirectoryServices.Protocols 5.0.1
- [linq2db 4.0.0](https://github.com/linq2db/linq2db/blob/9f70ca1da1b13c2b3df8ee0cf66b7c5b8f32524a/Directory.Packages.props#L32)
  - [Oracle.ManagedDataAccess.Core 2.19.140](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.19.140#dependencies-tab)
    - _no System.DirectoryServices.Protocols dependency_

**Comment by MaceWindu** [comment]
#64

**Comment by jswolf19** [comment]
Confirmed warning has disappeared. Thanks!
