### ISSUE TITLE
What format does the connection string use?

### ISSUE THREAD

**Issue by neo3exe** [linq2db/linq2db.LINQPad#77]
using the linqpad driver with postgres and would like to know if it's possible to include ssh tunnel settings in the connection string.

**Comment by MaceWindu** [comment]
We use `Npgsql`, so  it is npgsql connection string format https://www.npgsql.org/doc/connection-string-parameters.html

**Comment by neo3exe** [comment]
Thanks! looks like have to run the ssh tunnel separately afterall
