### ISSUE TITLE
Error when reading Guid from Sql Azure.

### ISSUE THREAD

**Issue by orges-kreka** [linq2db/linq2db.LINQPad#83]
I am trying to dump the results of a view, that view contains a column of type Guid ( sql type uniqueidentifier ) and so linqpad throws me this error:
![image](https://user-images.githubusercontent.com/90252043/209318475-adb5248d-6f30-43a8-af1e-7a31ba577004.png)
I was inspecting the object and i was seeing that its sql type is as nvarchar(36) and the property type is string.

How can i set a custom mapping for this like its done in the Linq2Db, [example](https://github.com/linq2db/linq2db/issues/1878#issuecomment-528613182).

**Comment by MaceWindu** [comment]
It doesn't look like issue in `linq2db.LINQPad` driver as I don't see any linq2db-related code in stack trace.

**Comment by MaceWindu** [comment]
Closing as it is not related to linq2db driver
