### ISSUE TITLE
No control over table name capitalization.

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db.LINQPad#89]
Tables and views in my databases often have names with specified capitalization, and previously the L2DB driver has left them intact. The new v5.0.0 driver however forces PascalCase on table and view names during refresh, with no apparent setting to disable this.

Example: View `VDRMSite` is generated as `VdrmSite`.

When testing code snippets or writing quick scripts the change in case for many of my table names wastes a ton of time as I have to search for the table in the tree view to find out what whacky name L2DB gave it.

Can we please get an option to use unmodified table names for class and property names where possible?

**Comment by wesj1s** [comment]
Yes please, and an option to retain __ prefix in field names. For the same reason.
