### ISSUE TITLE
Using SQL syntax when opening an SQLite DB

### ISSUE THREAD

**Issue by eitan-rapaport** [linq2db/linq2db.LINQPad#93]
Hey friends,

I've been trying to use this driver on LINQPad and it works like a charm when using LINQ syntax.
However, when I use the SQL syntax, I get the following error message no matter which table I try to select:

"SQL logic error
no such table: X"
(X being the table I choose)

The schema is properly shown on the left-hand side menu, I made sure that I am using the correct connection, and I tried multiple .NET versions, all ends the same way.

When I right-click on the DB connection, the "Use in current query" button is grayed out, meaning it's already selected.

Screenshot:
![image](https://github.com/linq2db/linq2db.LINQPad/assets/126149460/4b4caffc-4f7b-4b4a-b52a-b959290c96c2)

Now, an interesting thing to add here, is that all of the above happens on a remote machine I am working with.

In my local PC it works perfectly, and to make matters even more confusing, if I just go ahead and copy the query from my local machine to the remote one, it works perfectly fine. If I type the whole thing from scratch, I'll get an issue again.
Even worse is that if I copy the query from the remote machine and run it on my local machine, I'll start having the issue on my side too.

Both machines are using English(United States) keyboards.

I tried to search the web for this error, but haven't found any posts that followed through.

Does anyone have any suggestions?

Thanks!
Eitan

**Comment by MaceWindu** [comment]
There is an option on scaffold tab in connection settings to disable names normalization
