### ISSUE TITLE
Upgrade linq2db.LINQPad support LINQPad 8

### ISSUE THREAD

**Issue by kkbruce** [linq2db/linq2db.LINQPad#96]
LINQPad 8 is RTM, Upgrade linq2db.LINQPad to support LINQPad 8.

**Comment by MaceWindu** [comment]
What exactly should be upgraded? Do you have any issues with current release in linqpad 8?

**Comment by kkbruce** [comment]
@MaceWindu 

Connection is not working. 

Run a docker ms-sql container.

https://learn.microsoft.com/zh-tw/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash

Use connectionString `Server=localhost;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;` test by LINQPad 8 got error message:

![image](https://github.com/linq2db/linq2db.LINQPad/assets/2024682/bd2eefb8-efac-4107-9525-355b84699e8c)

![image](https://github.com/linq2db/linq2db.LINQPad/assets/2024682/9fffded8-8dc1-4d52-8e0e-385ee2b9f91d)

![image](https://github.com/linq2db/linq2db.LINQPad/assets/2024682/4ca67c0d-f7ee-44ea-8da1-313d5825f350)

![image](https://github.com/linq2db/linq2db.LINQPad/assets/2024682/022947d0-29a9-4a24-8b73-647353d5a438)

**Comment by viceroypenguin** [comment]
@kkbruce I can confirm that LinqPad 8 is working with the existing driver and MSSQL:
![image](https://github.com/linq2db/linq2db.LINQPad/assets/1992555/43eda315-e18a-4507-9936-9f8093f4f19a)

Like @MaceWindu said, add `Encrypt=false;` to your connection string and you should be able to access the docker MSSQL server.

**Comment by kkbruce** [comment]
`TrustServerCertificate=True` and `Encrypt=False` is working.
