### ISSUE TITLE
Upgrade dependency Azure.Identity package

### ISSUE THREAD

**Issue by kkbruce** [linq2db/linq2db.LINQPad#97]
![image](https://github.com/linq2db/linq2db.LINQPad/assets/2024682/eea9b24c-f80c-4e52-a9f4-4cab34ca9fba)

https://github.com/advisories/GHSA-5mfx-4wcx-rv27

**Comment by viceroypenguin** [comment]
This is an upstream issue in Microsoft.Data.SqlClient. Will have to wait for updated version of this package to address. You can manually reference a later of Azure.Identity if you want to remove the warning as a temporary fix. https://forum.linqpad.net/discussion/3035/nuget-package-vulnerability-in-managed-reference#latest

**Comment by MaceWindu** [comment]
Original issue https://github.com/dotnet/SqlClient/issues/2181 
Will be included in 5.2.0 release expected in January (?)
