### ISSUE TITLE
Unhandled error in method 'PreprocessObjectToWrite' for LINQPad8

### ISSUE THREAD

**Issue by embix** [linq2db/linq2db.LINQPad#98]
LP8 - When the query is set to a linqpad connection, dumping any _sequence_ of items will encounter the following error:

```
Unhandled error in method 'PreprocessObjectToWrite':
  The type initializer for 'LinqToDB.LlNQPad.ValueFormatter' threw an exception.
    at LinqToDB.LlNQPad.ValueFormatter.Format(Object value)
    at LinqToDB.LlNQPad.LinqToDBDriver.PreprocessObjectToWrite(Object& objectToWrite, ObjectGraphlnfo info)
```

LINQPad error appears with both versions 5.0.0 and 5.1.0 (for LINQPad versions 8.0.12 and 8.0.13).

**Comment by viceroypenguin** [comment]
Upon review, this has nothing to do with mariadb, or with any queries. Editing your question to relevant portions.

**Comment by viceroypenguin** [comment]
This is due to a Linqpad method signature being updated. Requires information from Joe (LP Dev) before fixing.

**Comment by MaceWindu** [comment]
Well, that's not good. If we address signature change it will break support for LP 5-7 versions

**Comment by viceroypenguin** [comment]
Per comment from Joe, the signature will be reverted in 8.0.14; as such, there is nothing to do on the linqpad side. @embix please look for 8.0.14, and re-open this ticket if the issue persists.
